# Generated by Django 6.0.2 on 2026-03-24 15:49

import django.core.validators
import django.db.models.deletion
import localflavor.in_.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomerProfile",
            fields=[
                (
                    "username",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                (
                    "password",
                    models.CharField(
                        max_length=100,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Password must be at least 8 characters long, include uppercase, lowercase, number and special character.",
                                regex="^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{8,}$",
                            )
                        ],
                    ),
                ),
                (
                    "pan_number",
                    localflavor.in_.models.INPANCardNumberField(
                        max_length=10, unique=True
                    ),
                ),
                (
                    "aadhar_number",
                    models.CharField(blank=True, max_length=12, null=True),
                ),
                ("full_name", models.CharField(default="Unknown", max_length=100)),
                (
                    "monthly_income",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "current_total_debt",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("cibil_score", models.IntegerField(default=600)),
                ("is_salaried", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="LoanRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("loan_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("tenure", models.IntegerField()),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("interest_rate", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="risk_engine.customerprofile",
                    ),
                ),
            ],
        ),
    ]
